# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/axi_spi_top_system_ila_4_0.xci
# IP: The module: 'axi_spi_top_system_ila_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/bd_bd17.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bd17 || ORIG_REF_NAME==bd_bd17} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/ip/ip_0/bd_bd17_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bd17_ila_lib_0 || ORIG_REF_NAME==bd_bd17_ila_lib_0} -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bd17_ila_lib_0 || ORIG_REF_NAME==bd_bd17_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bd17_ila_lib_0 || ORIG_REF_NAME==bd_bd17_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/ip/ip_0/bd_bd17_ila_lib_0_ooc.xdc

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/bd_bd17_ooc.xdc

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/axi_spi_top_system_ila_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_system_ila_4_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/axi_spi_top_system_ila_4_0.xci
# IP: The module: 'axi_spi_top_system_ila_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/bd_bd17.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bd17 || ORIG_REF_NAME==bd_bd17} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/ip/ip_0/bd_bd17_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bd17_ila_lib_0 || ORIG_REF_NAME==bd_bd17_ila_lib_0} -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bd17_ila_lib_0 || ORIG_REF_NAME==bd_bd17_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bd17_ila_lib_0 || ORIG_REF_NAME==bd_bd17_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/ip/ip_0/bd_bd17_ila_lib_0_ooc.xdc

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/bd_0/bd_bd17_ooc.xdc

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_4_0/axi_spi_top_system_ila_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_system_ila_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
