# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/axi_spi_top_system_ila_0_1.xci
# IP: The module: 'axi_spi_top_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/bd_bc97.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97 || ORIG_REF_NAME==bd_bc97} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_0/bd_bc97_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_ila_lib_0 || ORIG_REF_NAME==bd_bc97_ila_lib_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_1/bd_bc97_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_g_inst_0 || ORIG_REF_NAME==bd_bc97_g_inst_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_2/bd_bc97_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_aw_0 || ORIG_REF_NAME==bd_bc97_slot_0_aw_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_3/bd_bc97_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_w_0 || ORIG_REF_NAME==bd_bc97_slot_0_w_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_4/bd_bc97_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_b_0 || ORIG_REF_NAME==bd_bc97_slot_0_b_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_5/bd_bc97_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_ar_0 || ORIG_REF_NAME==bd_bc97_slot_0_ar_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_6/bd_bc97_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_r_0 || ORIG_REF_NAME==bd_bc97_slot_0_r_0} -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/axi_spi_top_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bc97_ila_lib_0 || ORIG_REF_NAME==bd_bc97_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bc97_ila_lib_0 || ORIG_REF_NAME==bd_bc97_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_0/bd_bc97_ila_lib_0_ooc.xdc

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/bd_bc97_ooc.xdc

# IP: D:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/axi_spi_top_system_ila_0_1.xci
# IP: The module: 'axi_spi_top_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/bd_bc97.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97 || ORIG_REF_NAME==bd_bc97} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_0/bd_bc97_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_ila_lib_0 || ORIG_REF_NAME==bd_bc97_ila_lib_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_1/bd_bc97_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_g_inst_0 || ORIG_REF_NAME==bd_bc97_g_inst_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_2/bd_bc97_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_aw_0 || ORIG_REF_NAME==bd_bc97_slot_0_aw_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_3/bd_bc97_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_w_0 || ORIG_REF_NAME==bd_bc97_slot_0_w_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_4/bd_bc97_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_b_0 || ORIG_REF_NAME==bd_bc97_slot_0_b_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_5/bd_bc97_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_ar_0 || ORIG_REF_NAME==bd_bc97_slot_0_ar_0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_6/bd_bc97_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bc97_slot_0_r_0 || ORIG_REF_NAME==bd_bc97_slot_0_r_0} -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/axi_spi_top_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bc97_ila_lib_0 || ORIG_REF_NAME==bd_bc97_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bc97_ila_lib_0 || ORIG_REF_NAME==bd_bc97_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/ip/ip_0/bd_bc97_ila_lib_0_ooc.xdc

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_system_ila_0_1/bd_0/bd_bc97_ooc.xdc
