# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/axi_spi_top_ddc_spec_0_1.xci
# IP: The module: 'axi_spi_top_ddc_spec_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/ddc_spec_dds_compiler_v6_0_i0/ddc_spec_dds_compiler_v6_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddc_spec_dds_compiler_v6_0_i0 || ORIG_REF_NAME==ddc_spec_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/ddc_spec_fir_compiler_v7_2_i0/ddc_spec_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddc_spec_fir_compiler_v7_2_i0 || ORIG_REF_NAME==ddc_spec_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/ddc_spec_mult_gen_v12_0_i0/ddc_spec_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddc_spec_mult_gen_v12_0_i0 || ORIG_REF_NAME==ddc_spec_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/ddc_spec_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddc_spec_fir_compiler_v7_2_i0 || ORIG_REF_NAME==ddc_spec_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/constrs/ddc_spec.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_ddc_spec_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/axi_spi_top_ddc_spec_0_1.xci
# IP: The module: 'axi_spi_top_ddc_spec_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/ddc_spec_dds_compiler_v6_0_i0/ddc_spec_dds_compiler_v6_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddc_spec_dds_compiler_v6_0_i0 || ORIG_REF_NAME==ddc_spec_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/ddc_spec_fir_compiler_v7_2_i0/ddc_spec_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddc_spec_fir_compiler_v7_2_i0 || ORIG_REF_NAME==ddc_spec_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/ddc_spec_mult_gen_v12_0_i0/ddc_spec_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddc_spec_mult_gen_v12_0_i0 || ORIG_REF_NAME==ddc_spec_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/ddc_spec_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddc_spec_fir_compiler_v7_2_i0 || ORIG_REF_NAME==ddc_spec_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_ddc_spec_0_1/constrs/ddc_spec.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_ddc_spec_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
